version: '3.7'

services:
  app:
    build: .
    container_name: back
    restart: on-failure
    env_file:
      - ./src/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: db
    env_file:
      - .env.db
    volumes:
      - kanalservice-db:/var/lib/postgresql/data





volumes:
  kanalservice-db: